spring:
  application:
    name: parking
  datasource:
    url: jdbc:postgresql://localhost:5432/parkee
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
